### ISSUE TITLE
좋아요 현황 저장방식 및 이용약관(?) 관련 질문

### ISSUE THREAD

**Issue by key-del-jeeinho** [theMomentTeam/The_Moment_Team#1]
https://www.the-moment.org/about
 IP 주소 등 개인을 식별할 수 있는 정보는 일절 저장되지 않습니다. 라고 되어있는데, 좋아요 현황은 그대로 유지되는것을 보았습니다. 혹시 어떤방식으로 이를 저장하는것인지 궁금합니다.

**Comment by sunrabbit123** [comment]
로컬스토리지로 예상됩니다
인증 절차를 만들 경우에 크게 세가지의 범주 안에서 해결합니다
1. 로컬스토리지
2. 쿠키
3. Authorization header

2번의 경우 아무값도 저장되지않는걸 확인하였기에 쿠키는 제외되며
3번의 경우도 마찬가지로 헤더에 아무값도 저장되지않더군요

직접 확인해보시는걸 추천드립니다

**Comment by jyeonjyan** [comment]
@sunrabbit123 답변 감사드립니다.
현재 좋아요에 관한 로직은 브라우저내에 로컬스토리지를 사용하는 방식으로 돌아가며
좋아요 관련 로직은 팀 내 충분한 의사결정을 통해 개선해 나갈 생각입니다. 감사합니다.

**Comment by key-del-jeeinho** [comment]
@Johnjihwan @sunrabbit123 친절한 답변 감사합니다. 앞으로 더욱 발전하는 the Moment 가 되면 좋겠네요 응원합니다! ㅎㅎ
