### ISSUE TITLE
좋아요 기능에 대한 사이드이펙트

### ISSUE THREAD

**Issue by sunrabbit123** [theMomentTeam/The_Moment_Team#2]
좋아요 기능의 경우 [해당 위치](https://www.the-moment.org/rank)에서 추가하고, 제거하는 것이 가능합니다.
문제라면 해당 위치에서는 총 10개까지의 의견밖에 나타내지않으며, 다른 의견들은 보여주지를 못합니다.
![image](https://user-images.githubusercontent.com/64676070/120981490-addd4e00-c7b2-11eb-8bd6-4aae2c49703e.png)

다른 의견에 대해서 좋아요를 누르고 싶어도 여타 의견들을 확인할 수 있는 유일한 [위치](https://www.the-moment.org/the_moment)가 해당 위치이지만, 좋아요를 누르지 못합니다.
![image](https://user-images.githubusercontent.com/64676070/120981739-f0068f80-c7b2-11eb-9110-9adc26a48daf.png)

이는 처음 올라 오게 된 Top 10의 좋아요만 누를 수 있도록 만들어진 로직이므로, 좋아요를 누르게 하는 의도와는 반대됩니다.

고로, [여기서도](https://www.the-moment.org/the_moment) 좋아요를 누를 수 있게 한다면, 좋아요를 누를 수 있는 의견이 10개로 한정되지는 않을 것 입니다.

**Comment by jyeonjyan** [comment]
좋아요 관련 로직은 FE와 BE 내부 의사결정이 필요한 부분이며
현재 팀 내에서는 이 부분에 있어서 이슈라고 인지하고 있습니다.

최대한 많은 사람들이 각자의 게시글에 공감을 받을 수 있는 방향으로 개선하겠습니다.
추가적으로, 이 이슈에 대한 해결이 될때 다시 공지하는걸로 하겠습니다. 감사합니다.
